import { ITokenSelectItem } from 'components/shared/TokenSelect/models';

export class TokenSelectMock {
  categories(): ITokenSelectItem[] {
    return [
      { value: '001', label: 'Сообщение', isParent: true, counter: 123 },
      {
        value: '002',
        label: 'Качество обслуживания',
        isParent: true,
        counter: 123,
      },
      { value: '003', label: 'ТО эл. объектов', isParent: true, counter: 123 },
      { value: '004', label: 'Жалоба', isParent: true, counter: 123 },
      { value: '005', label: 'Заявка' },
      { value: '006', label: 'Консультация', isParent: true, counter: 123 },
      { value: '007', label: 'Тех обслуживание электроприборов' },
      {
        value: '008',
        label: 'Демонтаж проводки',
        isParent: true,
        counter: 123,
      },
      { value: '009', label: 'Выезд специалиста на экспертизу' },
      { value: '010', label: 'Ремонт оборудования' },
      { value: '011', label: 'Замена счетчика', isParent: true, counter: 123 },
      { value: '012', label: 'Настройка системы' },
      {
        value: '013',
        label: 'Контроль безопасности',
        isParent: true,
        counter: 123,
      },
      { value: '014', label: 'Поддержка пользователей' },
      { value: '015', label: 'Обновление программного обеспечения' },
      { value: '016', label: 'Ремонт электросети' },
      {
        value: '017',
        label: 'Монтаж оборудования',
        isParent: true,
        counter: 123,
      },
      { value: '018', label: 'Удаление неисправностей' },
      { value: '019', label: 'Замена компонентов' },
      {
        value: '020',
        label: 'Инструктаж по безопасности',
        isParent: true,
        counter: 123,
      },
      { value: '021', label: 'Аварийное обслуживание' },
      { value: '022', label: 'Проектирование систем' },
      {
        value: '023',
        label: 'Мониторинг систем',
        isParent: true,
        counter: 123,
      },
      { value: '024', label: 'Регистрация новой техники' },
      { value: '025', label: 'Оценка состояния', isParent: true, counter: 123 },
      { value: '026', label: 'Проверка подключения' },
      { value: '027', label: 'Аудит системы' },
      {
        value: '028',
        label: 'Конфигурация сети',
        isParent: true,
        counter: 123,
      },
      { value: '029', label: 'Отчет о состоянии системы' },
      { value: '030', label: 'Восстановление системы' },
      {
        value: '031',
        label: 'Техническая поддержка',
        isParent: true,
        counter: 123,
      },
      { value: '032', label: 'Установка программного обеспечения' },
      { value: '033', label: 'Калибровка приборов' },
      {
        value: '034',
        label: 'Плановое обслуживание',
        isParent: true,
        counter: 123,
      },
      { value: '035', label: 'Срочный выезд специалиста' },
      { value: '036', label: 'Замена батарей' },
      {
        value: '037',
        label: 'Обучение персонала',
        isParent: true,
        counter: 123,
      },
      { value: '038', label: 'Ремонт электрощита' },
      { value: '039', label: 'Профилактические работы' },
      {
        value: '040',
        label: 'Технический осмотр',
        isParent: true,
        counter: 123,
      },
      { value: '041', label: 'Регистрация оборудования' },
      { value: '042', label: 'Поддержка устройств' },
      { value: '043', label: 'Настройка параметров сети' },
      {
        value: '044',
        label: 'Проверка датчиков',
        isParent: true,
        counter: 123,
      },
      { value: '045', label: 'Планирование мероприятий' },
      { value: '046', label: 'Устранение ошибок' },
      {
        value: '047',
        label: 'Консультация инженеров',
        isParent: true,
        counter: 123,
      },
      { value: '048', label: 'Проверка состояния оборудования' },
      { value: '049', label: 'Создание отчета' },
      { value: '050', label: 'Сбор данных', isParent: true, counter: 123 },
      { value: '051', label: 'Ремонт двигателей' },
      { value: '052', label: 'Модернизация системы' },
      {
        value: '053',
        label: 'Тестирование оборудования',
        isParent: true,
        counter: 123,
      },
      { value: '054', label: 'Устранение неполадок' },
      { value: '055', label: 'Оценка качества' },
      {
        value: '056',
        label: 'Анализ работоспособности',
        isParent: true,
        counter: 123,
      },
      { value: '057', label: 'Программирование оборудования' },
      { value: '058', label: 'Настройка устройств' },
      {
        value: '059',
        label: 'Контроль исполнения',
        isParent: true,
        counter: 123,
      },
      { value: '060', label: 'Проверка соединений' },
      { value: '061', label: 'Удаленное обслуживание' },
      {
        value: '062',
        label: 'Управление проектом',
        isParent: true,
        counter: 123,
      },
      { value: '063', label: 'Разработка документации' },
      { value: '064', label: 'Создание инструкций' },
      {
        value: '065',
        label: 'Установка нового оборудования',
        isParent: true,
        counter: 123,
      },
      { value: '066', label: 'Монтаж датчиков' },
      { value: '067', label: 'Подключение к сети' },
      {
        value: '068',
        label: 'Обучение операторов',
        isParent: true,
        counter: 123,
      },
      { value: '069', label: 'Поддержка системы безопасности' },
      { value: '070', label: 'Технический анализ' },
      { value: '071', label: 'Отладка системы', isParent: true, counter: 123 },
      { value: '072', label: 'Аварийный вызов' },
      { value: '073', label: 'Обновление данных' },
      {
        value: '074',
        label: 'Резервное копирование',
        isParent: true,
        counter: 123,
      },
      { value: '075', label: 'Тестирование новых функций' },
      { value: '076', label: 'Проверка обновлений' },
      {
        value: '077',
        label: 'Составление плана обслуживания',
        isParent: true,
        counter: 123,
      },
      { value: '078', label: 'Удаленное управление' },
      { value: '079', label: 'Проверка питания' },
      {
        value: '080',
        label: 'Создание графиков работ',
        isParent: true,
        counter: 123,
      },
      {
        value: '081',
        label: 'Анализ энергопотребления',
        isParent: true,
        counter: 123,
      },
      { value: '082', label: 'Управление оборудованием' },
      { value: '083', label: 'Поддержка программного обеспечения' },
      { value: '084', label: 'Отчет об ошибках', isParent: true, counter: 123 },
      { value: '085', label: 'Тестирование на совместимость' },
      { value: '086', label: 'Ремонт кабелей' },
      {
        value: '087',
        label: 'Оценка надежности',
        isParent: true,
        counter: 123,
      },
      { value: '088', label: 'Мониторинг безопасности' },
      { value: '089', label: 'Диагностика системы' },
      {
        value: '090',
        label: 'Отключение оборудования',
        isParent: true,
        counter: 123,
      },
      { value: '091', label: 'Разработка улучшений' },
      { value: '092', label: 'Подготовка отчетности' },
      {
        value: '093',
        label: 'Сборка компонентов',
        isParent: true,
        counter: 123,
      },
      { value: '094', label: 'Оптимизация сети' },
      { value: '095', label: 'Монтаж сигнализации' },
      { value: '096', label: 'Анализ данных', isParent: true, counter: 123 },
      { value: '097', label: 'Регистрация неисправностей' },
      { value: '098', label: 'Настройка интерфейса' },
      {
        value: '099',
        label: 'Планирование замен',
        isParent: true,
        counter: 123,
      },
      { value: '100', label: 'Контроль качества' },
      { value: '101', label: 'Настройка профилей доступа' },
      {
        value: '102',
        label: 'Диагностика подключения',
        isParent: true,
        counter: 123,
      },
      { value: '103', label: 'Создание тестовых сценариев' },
      { value: '104', label: 'Согласование документации' },
      {
        value: '105',
        label: 'Планирование аудитов',
        isParent: true,
        counter: 123,
      },
      { value: '106', label: 'Проверка системы оповещений' },
      { value: '107', label: 'Настройка безопасности' },
      {
        value: '108',
        label: 'Регламентное обслуживание',
        isParent: true,
        counter: 123,
      },
      { value: '109', label: 'Планирование обновлений' },
      { value: '110', label: 'Проверка доступности' },
      {
        value: '111',
        label: 'Удаленная поддержка',
        isParent: true,
        counter: 123,
      },
      { value: '112', label: 'Тестирование на отказоустойчивость' },
      { value: '113', label: 'Анализ состояния системы' },
      {
        value: '114',
        label: 'Планирование ремонта',
        isParent: true,
        counter: 123,
      },
      { value: '115', label: 'Подключение периферии' },
      { value: '116', label: 'Обновление базы данных' },
      {
        value: '117',
        label: 'Интеграция с системами',
        isParent: true,
        counter: 123,
      },
      { value: '118', label: 'Контроль загрузки' },
      { value: '119', label: 'Выдача разрешений' },
      {
        value: '120',
        label: 'Мониторинг ресурсов',
        isParent: true,
        counter: 123,
      },
      { value: '121', label: 'Проверка лицензий' },
      { value: '122', label: 'Оперативная диагностика' },
      {
        value: '123',
        label: 'Обслуживание сети',
        isParent: true,
        counter: 123,
      },
      { value: '124', label: 'Поддержка взаимодействия' },
      { value: '125', label: 'Настройка системы резервирования' },
      {
        value: '126',
        label: 'Разработка планов работы',
        isParent: true,
        counter: 123,
      },
      { value: '127', label: 'Составление отчетов по обслуживанию' },
      { value: '128', label: 'Проверка соединений' },
      {
        value: '129',
        label: 'Контроль состояния устройств',
        isParent: true,
        counter: 123,
      },
      { value: '130', label: 'Настройка доступа' },
      { value: '131', label: 'Тестирование безопасности' },
      {
        value: '132',
        label: 'Планирование использования',
        isParent: true,
        counter: 123,
      },
      { value: '133', label: 'Анализ инцидентов' },
      { value: '134', label: 'Установка защитного ПО' },
      {
        value: '135',
        label: 'Поддержка пользователей',
        isParent: true,
        counter: 123,
      },
      { value: '136', label: 'Оптимизация работы' },
      { value: '137', label: 'Подключение к системам мониторинга' },
      { value: '138', label: 'Проверка отчетов', isParent: true, counter: 123 },
      { value: '139', label: 'Ремонт периферии' },
      { value: '140', label: 'Отчет об инцидентах' },
      {
        value: '141',
        label: 'Контроль выполнения задач',
        isParent: true,
        counter: 123,
      },
      { value: '142', label: 'Установка защитных модулей' },
      { value: '143', label: 'Тестирование компонентов' },
      {
        value: '144',
        label: 'Анализ производительности',
        isParent: true,
        counter: 123,
      },
      { value: '145', label: 'Разработка процедур' },
      { value: '146', label: 'Сбор статистики' },
      {
        value: '147',
        label: 'Поддержка баз данных',
        isParent: true,
        counter: 123,
      },
      { value: '148', label: 'Контроль пропускной способности' },
      { value: '149', label: 'Обслуживание устройств' },
      {
        value: '150',
        label: 'Создание инструкций по безопасности',
        isParent: true,
        counter: 123,
      },
      { value: '151', label: 'Настройка системы контроля' },
      { value: '152', label: 'Сбор отчетов' },
      {
        value: '153',
        label: 'Планирование замены оборудования',
        isParent: true,
        counter: 123,
      },
      { value: '154', label: 'Мониторинг подключения' },
      { value: '155', label: 'Настройка защиты сети' },
      {
        value: '156',
        label: 'Анализ статистики',
        isParent: true,
        counter: 123,
      },
      { value: '157', label: 'Поддержка функционала' },
      { value: '158', label: 'Контроль за состоянием' },
      {
        value: '159',
        label: 'Планирование профилактики',
        isParent: true,
        counter: 123,
      },
      { value: '160', label: 'Обновление драйверов' },
      { value: '161', label: 'Проверка аппаратной совместимости' },
      {
        value: '162',
        label: 'Разработка инструкций',
        isParent: true,
        counter: 123,
      },
      { value: '163', label: 'Ремонт сетевого оборудования' },
      { value: '164', label: 'Обслуживание интерфейсов' },
      { value: '165', label: 'Контроль рисков', isParent: true, counter: 123 },
      { value: '166', label: 'Тестирование на производительность' },
      { value: '167', label: 'Настройка периферии' },
      {
        value: '168',
        label: 'Планирование ресурсов',
        isParent: true,
        counter: 123,
      },
      { value: '169', label: 'Мониторинг нагрузок' },
      { value: '170', label: 'Установка модулей' },
      { value: '171', label: 'Анализ сбоев', isParent: true, counter: 123 },
      { value: '172', label: 'Разработка отчетов' },
      { value: '173', label: 'Проверка данных' },
      {
        value: '174',
        label: 'Оптимизация процессов',
        isParent: true,
        counter: 123,
      },
      { value: '175', label: 'Обновление интерфейсов' },
      { value: '176', label: 'Поддержка связи' },
      {
        value: '177',
        label: 'Настройка аналитики',
        isParent: true,
        counter: 123,
      },
      { value: '178', label: 'Проверка совместимости' },
      { value: '179', label: 'Диагностика оборудования' },
      {
        value: '180',
        label: 'Оценка эффективности',
        isParent: true,
        counter: 123,
      },
      { value: '181', label: 'Настройка отчетности' },
      { value: '182', label: 'Обслуживание защитных систем' },
      {
        value: '183',
        label: 'Оптимизация настроек',
        isParent: true,
        counter: 123,
      },
      { value: '184', label: 'Ремонт периферии' },
      { value: '185', label: 'Мониторинг энергопотребления' },
      {
        value: '186',
        label: 'Обновление безопасности',
        isParent: true,
        counter: 123,
      },
      { value: '187', label: 'Проверка производительности' },
      { value: '188', label: 'Техническая поддержка' },
      {
        value: '189',
        label: 'Обслуживание систем',
        isParent: true,
        counter: 123,
      },
      { value: '190', label: 'Управление лицензиями' },
      { value: '191', label: 'Настройка системы' },
      {
        value: '192',
        label: 'Мониторинг процессов',
        isParent: true,
        counter: 123,
      },
      { value: '193', label: 'Контроль ошибок' },
      { value: '194', label: 'Поддержка обновлений' },
      {
        value: '195',
        label: 'Проверка стабильности',
        isParent: true,
        counter: 123,
      },
      { value: '196', label: 'Диагностика сетей' },
      { value: '197', label: 'Мониторинг отказов' },
      { value: '198', label: 'Обновление ПО', isParent: true, counter: 123 },
      { value: '199', label: 'Поддержка тестирования' },
      { value: '200', label: 'Оптимизация операций' },
    ];
  }

  branches(): ITokenSelectItem[] {
    return [
      { value: 'branch_001', label: 'Центральный филиал' },
      { value: 'branch_002', label: 'Северный филиал' },
      { value: 'branch_003', label: 'Южный филиал' },
      { value: 'branch_004', label: 'Западный филиал' },
      { value: 'branch_005', label: 'Восточный филиал' },
      { value: 'branch_006', label: 'Уральский филиал' },
      { value: 'branch_007', label: 'Поволжский филиал' },
      { value: 'branch_008', label: 'Юго-Восточный филиал' },
      { value: 'branch_009', label: 'Кавказский филиал' },
      { value: 'branch_010', label: 'Приморский филиал' },
      { value: 'branch_011', label: 'Сибирский филиал' },
      { value: 'branch_012', label: 'Амурский филиал' },
      { value: 'branch_013', label: 'Дальневосточный филиал' },
      { value: 'branch_014', label: 'Центрально-Черноземный филиал' },
      { value: 'branch_015', label: 'Татарстанский филиал' },
      { value: 'branch_016', label: 'Башкирский филиал' },
      { value: 'branch_017', label: 'Нижегородский филиал' },
      { value: 'branch_018', label: 'Северо-Кавказский филиал' },
      { value: 'branch_019', label: 'Крымский филиал' },
      { value: 'branch_020', label: 'Северный Урал' },
      { value: 'branch_021', label: 'Забайкальский филиал' },
      { value: 'branch_022', label: 'Чеченский филиал' },
      { value: 'branch_023', label: 'Алтайский филиал' },
      { value: 'branch_024', label: 'Карельский филиал' },
      { value: 'branch_025', label: 'Кузбасский филиал' },
      { value: 'branch_026', label: 'Мурманский филиал' },
      { value: 'branch_027', label: 'Арктический филиал' },
      { value: 'branch_028', label: 'Сахалинский филиал' },
      { value: 'branch_029', label: 'Хакасия' },
      { value: 'branch_030', label: 'Ямало-Ненецкий филиал' },
      { value: 'branch_031', label: 'Чувашский филиал' },
      { value: 'branch_032', label: 'Рязанский филиал' },
      { value: 'branch_033', label: 'Тверской филиал' },
      { value: 'branch_034', label: 'Тамбовский филиал' },
      { value: 'branch_035', label: 'Пензенский филиал' },
      { value: 'branch_036', label: 'Калужский филиал' },
      { value: 'branch_037', label: 'Орловский филиал' },
      { value: 'branch_038', label: 'Белгородский филиал' },
      { value: 'branch_039', label: 'Брянский филиал' },
      { value: 'branch_040', label: 'Костромской филиал' },
    ];
  }

  specialists(): ITokenSelectItem[] {
    return [
      { value: 'spec_001', label: 'Инженер по техническому обслуживанию' },
      { value: 'spec_002', label: 'Техник по монтажу' },
      { value: 'spec_003', label: 'Электрик' },
      { value: 'spec_004', label: 'Мастер по ремонту оборудования' },
      { value: 'spec_005', label: 'Специалист по безопасности' },
      { value: 'spec_006', label: 'Консультант по IT' },
      { value: 'spec_007', label: 'Программист' },
      { value: 'spec_008', label: 'Специалист по обслуживанию сетей' },
      { value: 'spec_009', label: 'Аудитор системы' },
      { value: 'spec_010', label: 'Проектировщик систем' },
      { value: 'spec_011', label: 'Контролер качества' },
      { value: 'spec_012', label: 'Менеджер проекта' },
      { value: 'spec_013', label: 'Инженер по калибровке' },
      { value: 'spec_014', label: 'Сервисный инженер' },
      { value: 'spec_015', label: 'Специалист по ремонту' },
      { value: 'spec_016', label: 'Оператор техподдержки' },
      { value: 'spec_017', label: 'Инженер-проектировщик' },
      { value: 'spec_018', label: 'Электромонтажник' },
      { value: 'spec_019', label: 'Разработчик программного обеспечения' },
      { value: 'spec_020', label: 'Технический консультант' },
      { value: 'spec_021', label: 'Системный администратор' },
      { value: 'spec_022', label: 'Мастер по установке оборудования' },
      { value: 'spec_023', label: 'Специалист по конфигурации сетей' },
      { value: 'spec_024', label: 'Инженер по эксплуатации' },
      { value: 'spec_025', label: 'Специалист по замене компонентов' },
      { value: 'spec_026', label: 'Оператор системного мониторинга' },
      { value: 'spec_027', label: 'Техник по поддержке пользователей' },
      { value: 'spec_028', label: 'Консультант по безопасности' },
      { value: 'spec_029', label: 'Специалист по обучению персонала' },
      { value: 'spec_030', label: 'Администратор технической поддержки' },
      { value: 'spec_031', label: 'Эксперт по оценке состояния' },
      { value: 'spec_032', label: 'Мастер по монтажу оборудования' },
      { value: 'spec_033', label: 'Инженер по техобслуживанию' },
      { value: 'spec_034', label: 'Оператор аварийного обслуживания' },
      { value: 'spec_035', label: 'Специалист по плановому обслуживанию' },
      { value: 'spec_036', label: 'Эксперт по безопасности' },
      { value: 'spec_037', label: 'Мастер по диагностике неисправностей' },
      { value: 'spec_038', label: 'Техник по ремонту электросети' },
      { value: 'spec_039', label: 'Инженер по калибровке оборудования' },
      { value: 'spec_040', label: 'Специалист по техническому осмотру' },
    ];
  }

  segments(): ITokenSelectItem[] {
    return [
      { value: 'seg_001', label: 'Аудитория Магнит Опт' },
      { value: 'seg_002', label: 'Лояльные 321' },
      { value: 'seg_003', label: 'Лояльные 231' },
      {
        value: 'seg_004',
        label:
          'Аудитория 16 - 20 лет Магнит Семейный, г. Краснодар, ул. Российская, 331-333',
      },
      { value: 'seg_005', label: 'Аудитория Магнит Семейный' },
      { value: 'seg_006', label: 'Аудитория до 18 лет Магнит Аптека' },
      { value: 'seg_007', label: 'Аудитория старше 18 лет Магнит Аптека' },
      { value: 'seg_008', label: 'Аудитория до 25 лет Магнит Косметик' },
      { value: 'seg_009', label: 'Аудитория старше 25 лет Магнит Косметик' },
      { value: 'seg_010', label: 'Лояльные 432' },
      {
        value: 'seg_011',
        label: 'Аудитория с доходом выше среднего, Магнит у дома',
      },
      { value: 'seg_012', label: 'Аудитория до 30 лет, Магнит Универсам' },
      { value: 'seg_013', label: 'Семейные пары Магнит Опт' },
      { value: 'seg_014', label: 'Аудитория с детьми, Магнит у дома' },
      { value: 'seg_015', label: 'Пенсионеры Магнит Аптека' },
      { value: 'seg_016', label: 'Аудитория 25 - 35 лет, Магнит Опт' },
      { value: 'seg_017', label: 'Аудитория 35 - 45 лет, Магнит Семейный' },
      { value: 'seg_018', label: 'Лояльные покупатели Магнит у дома' },
      { value: 'seg_019', label: 'Аудитория до 20 лет, Магнит Опт' },
      { value: 'seg_020', label: 'Аудитория 45+ лет, Магнит Аптека' },
      { value: 'seg_021', label: 'Аудитория до 16 лет, Магнит Косметик' },
      { value: 'seg_022', label: 'Семейные покупатели Магнит Семейный' },
      { value: 'seg_023', label: 'Аудитория до 35 лет, Магнит Универсам' },
      {
        value: 'seg_024',
        label: 'Аудитория с доходом ниже среднего, Магнит у дома',
      },
      { value: 'seg_025', label: 'Лояльные 145' },
      { value: 'seg_026', label: 'Аудитория до 40 лет, Магнит Опт' },
      { value: 'seg_027', label: 'Молодые семьи Магнит у дома' },
      { value: 'seg_028', label: 'Аудитория 55+ лет, Магнит Аптека' },
      {
        value: 'seg_029',
        label: 'Аудитория с высоким доходом, Магнит Косметик',
      },
      {
        value: 'seg_030',
        label: 'Покупатели со скидочными картами, Магнит Универсам',
      },
      { value: 'seg_031', label: 'Аудитория 20 - 25 лет, Магнит у дома' },
      { value: 'seg_032', label: 'Новые клиенты Магнит Опт' },
      { value: 'seg_033', label: 'Аудитория после 50 лет, Магнит Аптека' },
      { value: 'seg_034', label: 'Постоянные покупатели Магнит Косметик' },
      { value: 'seg_035', label: 'Аудитория без скидок, Магнит Семейный' },
      { value: 'seg_036', label: 'Лояльные клиенты, Магнит у дома' },
      { value: 'seg_037', label: 'Семейные покупатели Магнит Аптека' },
      { value: 'seg_038', label: 'Аудитория 18 - 30 лет, Магнит Опт' },
      { value: 'seg_039', label: 'Аудитория 40+, Магнит Косметик' },
      { value: 'seg_040', label: 'Аудитория до 50 лет, Магнит Универсам' },
    ];
  }
}
